excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - line_length

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
